sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-2.26
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - mesa-common-dev
            - libx11-dev
            - libxcursor-dev
            - libxrandr-dev
            - libxi-dev
            - uuid-dev
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/Deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # Download CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.tar.gz"
      mkdir cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  - cd ..

script:
  - INSTALL_DIR="${TRAVIS_BUILD_DIR}/Install"
  - mkdir ${INSTALL_DIR}
  - mkdir Build && cd Build
  - cmake .. -DCMAKE_INSTALL_PREFIX:STRING=${INSTALL_DIR}
  - make -j
  - make install
  
after_success:
  - cd ..
  - today=`date +%Y-%m-%d`
  - filename=bsf_${today}_${TRAVIS_OS_NAME}.zip
  - cd ${INSTALL_DIR}
  - echo $TRAVIS_EVENT_TYPE
  - zip -rq ${filename} ./*
  - curl -v --ftp-create-dirs -T ${filename} -u ${FTP_USER}:${FTP_PASSWORD} ${FTP_DESTINATION}