image: Visual Studio 2017
platform: x64
configuration: OptimizedDebug
clone_folder: C:\Projects\bsf

environment:
  FTP_USER:
    secure: 6/QO2m0slpHVIaSvCgshSQ==
  FTP_PASSWORD:
    secure: NZnU8rVuQ/CeRYWBRObDfQ==
  FTP_HOST:
    secure: vkR/qaZuHZ7k7iZQBfLlNYJzx/+rzkhRlOloJq7o0mk=

build_script:
  - cmd: set INSTALL_DIR=C:/Projects/bsf/CI
  - cmd: mkdir "%INSTALL_DIR%"
  - cmd: mkdir Build
  - cmd: cd Build
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:STRING=%INSTALL_DIR% ..
  - cmd: cmake --build ./ --config OptimizedDebug
  - cmd: cmake --build ./ --config OptimizedDebug --target INSTALL

after_build:
 - ps: $buildName = "$(Get-Date -format dd.MM.yyyy)"
 - ps: 7z a bsf_Win64_$buildName.zip ./CI/* -xr!*pdb
 - ps: 7z a bsf_Win64_Symbols_$buildName.zip ./CI/*pdb -r

artifacts:
  - path: bsf_Win64_$(APPVEYOR_BUILD_NUMBER).zip
    name: bsf_Win64_$(APPVEYOR_BUILD_NUMBER)
    type: zip
  - path: bsf_Win64_Symbols_$(APPVEYOR_BUILD_NUMBER).zip
    name: bsf_Win64_Symbols_$(APPVEYOR_BUILD_NUMBER)
    type: zip

deploy:
  - provider: FTP
    protocol: ftp
    host: $(FTP_HOST)
    username: $(FTP_USER)
    password: $(FTP_PASSWORD)
    folder: bsfBuilds
    application:
    active_mode: false
    beta: true
    debug: true
    on:
      APPVEYOR_SCHEDULED_BUILD: true
